# Generated by Django 4.0.1 on 2022-01-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявление'},
        ),
        migrations.AddField(
            model_name='CustomUser',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
